name: pylab
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pyinstaller
  - gdal
  - rasterio
  - matplotlib
  - torch
  - ultralytics
  - onnxruntime
  - opencv-python
  - conda-pack
  - pip
  - customtkinter
  - pip:
    - nuitka
    - pillow
    - numpy
    - pytest
    - black
    - isort 